spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: root

server:
  port: 8083

resilience4j:
  circuitbreaker:
    instances:
      productService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
